version: '3'
services:
  clickhouse:
    image: pycontribs/centos:7
    container_name: clickhouse-01
    restart: unless-stopped
    entrypoint: "sleep infinity"

  vector-01:
    image: pycontribs/ubuntu
    container_name: vector-01
    restart: unless-stopped
    entrypoint: "sleep infinity"
